### ISSUE TITLE
How does the Calculated Column Works?

### ISSUE THREAD

**Issue by arivera511** [Mgiepz/saiku-adhoc#157]
Hi , i was wondering how was the Formula field on the calculated column works?, How can i make a Formula like adding two metadata objects?

Thanks for all this work, its amazing how saiku reporting let you make usefull reports so quickly

Regards

**Comment by Mgiepz** [comment]
The formula field accepts OpenFormula expressions, the same as in Pentaho-Reportdesigner. If you want to add two
numeric columns you have to write:
[ColumnA]+[ColumnB]
If you want to concatenate two string columns and some text:
"This is " & [ColumnC] & " and " & [ColumnD]

Beware: The resulting field is always a string at the moment so you can't sum up a calculated column. This is due to 
a limitation in the CDA and i am trying to find a way to fix this.

**Comment by dguiarj** [comment]
Hi,
Considering "OpenFormula expressions" I research at google and follow the link https://www.oasis-open.org/committees/download.php/16826/openformula-spec-20060221.html
I was trying to get a better grasp of what I could use in my calculated columns (I really need to make it possible to format)...  what I get from the tests was:

[ColumnA]+[ColumnB] - Works
SUM([ColumnA];[ColumnB]) - Works
[ColumnA]+[ColumnB]/2 - Works
SUM([ColumnA];[ColumnB]/2;[ColumnC]) - works
"USD$ " & [Em 2h]+[Em 4h]+[Em 6h]/3 - works
DATE([ColumnA];[ColumnB];[ColumnC]) - works (2013;01;02)
But:
ROUND([ColumnA];2) - dont work
ROUND([ColumnA]+[ColumnB];2) - dont work
TRUNC([ColumnA];2) - dont work
AVERAGE(2;4) - dont work

Is there a way to format ? ( the format filed is disable)  and is there some where to look for the avaliable expressions?

**Comment by Mgiepz** [comment]
We are using lib-formula from pentaho, so only the openformula expression that are implemented therein are available.
Regarding the formatting we have the problem that the calculated columns are generated in cda which returns them as string, so we cannot apply format masks. In the new saiku-reporting we are considering to put the calculation into the report rather than in the datasource

Von meinem iPad gesendet

Am 02.05.2013 um 13:24 schrieb dguiarj notifications@github.com:

**Comment by dguiarj** [comment]
Here it goes some "stretching"... since it goes as text... its possible to use the "FIXED" expression... so
FIXED(SUM([ColumnA];[ColumnB]);2) - works (gives 2 decimal format) BUT it loses the number format from the metadata... (also loses the format from locale)
Going a little futher is possible to:
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FIXED(SUM([ColumnA];[ColumnB]);2);",";"-");".";",");"-";".")

"High level POG" (pt-br joke)
